@Echo OFF
 on break cancel
echo.

:DESCRIPTION: Post-processor for the "net use" command.  See display-drive-mapping.jpg for sample.
rem validate-environment-variables UnicodeOutputDefault

REM 2.5 net use|sed "s/ *Microsoft Windows Network *//"|grep -i -v new.connections|grep -i -v status|grep -i -v "[\-][\-][\-]"|call strip-blank-lines|grep -i -v "%=^[\t ]*$"|grep -i -v completed.successfully | sed -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/"  -e "s/^/%ANSI_RESET%/"|cat
rem 2.5 net use|sed "s/ *Microsoft Windows Network *//"|grep -i -v new.connections|grep -i -v status|grep -i -v "[\-][\-][\-]"|grep -i -v "%=^[\t ]*$"|grep -i -v completed.successfully | sed -e "/^[[:space:]]*$/d" -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/"  -e "s/^/%ANSI_RESET%/" |cat
rem 2.0 net use|grep -i -v new.connections|grep -i -v status|grep -i -v "[\-][\-][\-]"|grep -i -v "%=^[\t ]*$"|grep -i -v completed.successfully | sed -e "s/ *Microsoft Windows Network *//" -e "/^[[:space:]]*$/d" -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/"  -e "s/^/%ANSI_RESET%/" |cat
rem 1.7 net use|grep -i -v status|grep -i -v "[\-][\-][\-]"|grep -i -v "%=^[\t ]*$"|grep -i -v completed.successfully | sed -e "/New connections will be remembered/d" -e "s/ *Microsoft Windows Network *//" -e "/^[[:space:]]*$/d" -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/"  -e "s/^/%ANSI_RESET%/" |cat
rem 1.5 net use                  |grep -i -v "[\-][\-][\-]"|grep -i -v "%=^[\t ]*$"|grep -i -v completed.successfully | sed -e "/New connections will be remembered/d" -e "/Status.*Local.*Remote.*Network/d" -e "s/ *Microsoft Windows Network *//" -e "/^[[:space:]]*$/d" -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/"  -e "s/^/%ANSI_RESET%/" |cat
rem 1.2 net use |grep -i -v "%=^[\t ]*$"|grep -i -v completed.successfully | sed -e "/New connections will be remembered/d" -e "/\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-/d" -e "/Status.*Local.*Remote.*Network/d" -e "s/ *Microsoft Windows Network *//" -e "/^[[:space:]]*$/d" -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/"  -e "s/^/%ANSI_RESET%/" |cat
rem 0.9 net use                         |grep -i -v completed.successfully | sed -e "/New connections will be remembered/d" -e "/\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-/d" -e "/Status.*Local.*Remote.*Network/d" -e "s/ *Microsoft Windows Network *//" -e "/^[[:space:]]*$/d" -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/"  -e "s/^/%ANSI_RESET%/" |cat
rem 0.6 - .13 w/o the cat        net use | sed -e "/New connections will be remembered/d" -e "/\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-/d" -e "/command completed/d" -e "/Status.*Local.*Remote.*Network/d" -e "s/ *Microsoft Windows Network *//" -e "/^[[:space:]]*$/d" -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/"  -e "s/^/%ANSI_RESET%/" | cat
rem 0.15 WITH the cat
echos %CONCEAL_ON% %+ timer /2 on %+ echos %CONCEAL_OFF%
rem until 20240526 net use | sed -e "/New connections will be remembered/d" -e "/\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-/d" -e "/command completed/d" -e "/Status.*Local.*Remote.*Network/d" -e "s/ *Microsoft Windows Network *//" -e "/^[[:space:]]*$/d" -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e"s/^OK/%ANSI_GREEN%OK%ANSI_COLOR_RUN%/" -e "s/:/%ANSI_YELLOW%%FAINT_ON%:%FAINT_OFF%%@ANSI_FG[128,140,128]/" -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/"  -e "s/^/%ANSI_RESET%/" | cat_fast
rem option //UnicodeOutput=yes
rem net use |    sed -e "/New connections will be remembered/d" -e "/\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-/d" -e "/command completed/d" -e "/Status.*Local.*Remote.*Network/d" -e "s/ *Microsoft Windows Network *//" -e "/^[[:space:]]*$/d" -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e"s/^OK/%ANSI_GREEN%OK%ANSI_COLOR_RUN%/" -e "s/:/%ANSI_YELLOW%%FAINT_ON%:%FAINT_OFF%%@ANSI_FG[128,140,128]/" -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/" -e   "s/\(Unavailable\)\(.*\)\(\\\\\\\\\)/%BLINK_ON%%@ANSI_BG[25,0,0]%ITALICS_ON%%ANSI_COLOR_BRIGHT_RED%\1\2%ITALICS_OFF%%BLINK_OFF%\3/" -e   "s/\(Unavailable\)\(.*\)\(33m\)/\1\2/"  |    cat_fast
   (net use |:u8 sed -e "/New connections will be remembered/d" -e "/\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-/d" -e "/command completed/d" -e "/Status.*Local.*Remote.*Network/d" -e "s/ *Microsoft Windows Network *//" -e "/^[[:space:]]*$/d" -e "s/\\\\\\\\/PLACEHOLDER/g"  -e "s/\\\\\([^\\]\)/\\\\%ITALICS_ON%%UNDERLINE_OFF%\1/g; s/PLACEHOLDER/\\\\\\\\/g"  -e "s/GOLIATH/%MACHINE_COLOR_GOLIATH%%FAINT_ON%GOLIATH%FAINT_OFF%/g"  -e "s/WYVERN\([0-9a-zA-Z]*\)/%MACHINE_COLOR_WYVERN%WYVERN\1 %ITALICS_OFF%%EMOJI_CASTLE%/g"  -e "s/DEMONA\([0-9a-zA-Z]*\)/%MACHINE_COLOR_DEMONA%DEMONA\1 %ITALICS_OFF%%EMOJI_MACHINE_DEMONA%/g"  -e"s/^OK/%ANSI_GREEN%OK%ANSI_COLOR_RUN%/" -e "s/:/%ANSI_YELLOW%%FAINT_ON%:%FAINT_OFF%%@ANSI_FG[128,140,128]/" -e "s/THAILOG\([0-9a-zA-Z]*\)/%MACHINE_COLOR_THAILOG%THAILOG\1 %ITALICS_OFF%%EMOJI_MACHINE_THAILOG%/g"  -e "s/$/%ITALICS_OFF%%ANSI_RESET%/" -e   "s/\(Unavailable\)\(.*\)\(\\\\\\\\\)/%BLINK_ON%%@ANSI_BG[25,0,0]%ITALICS_ON%%ANSI_COLOR_BRIGHT_RED%\1\2%ITALICS_OFF%%BLINK_OFF%\3/" -e   "s/\(Unavailable\)\(.*\)\(33m\)/\1\2/") |:u8 cat_fast
rem blah -e "s/\(Unavailable\)\(.*\)\(%ANSI_YELLOW%\)/\1\2/" -e "s/^/%ANSI_RESET%/" 
rem .4 with cat_fast but first one is 2.5 - wsl's cat was 0.03 but doesn't work outside of WSL even tho it's supposed to and also has a slow startup time
rem option //UnicodeOutput=%UnicodeOutputDefault%
echos %CONCEAL_ON% %+ timer /2 off %+ echos %CONCEAL_OFF%

