@Echo OFF

REM call debug "Setting emojis..."

if "%1" eq "force"               (goto :Main_Branch)
if  "1" eq %EMOJIS_HAVE_BEEN_SET (goto :Already_Set)
if "%1" eq "generate"            (fix_unicode_filenames.py script|:u8sort|:u8uniq >:u8%bat%\emoji.env.generated.on.%_ISODATE.dont.forget.to.move.manual.stuff.at.end.of.previous.versions)

:Main_Branch

        rem Load emojis generated by our script: 
                set /r c:\bat\emoji.env           

        rem Flag that the emojis have been defined so we don't do this over and over:
                set EMOJIS_HAVE_BEEN_SET=1         

:Already_Set
:END
setdos /X0
