@SET HEX_MAGENTA_GOOD=FF00FF
@SET HEX_ORANGE_UNASSUMING=CF5500
@SET HEX_ORANGE_DARK_PUMPKIN=DF5500
@rem HEX=%HEX_MAGENTA_GOOD%
@set HEX=%HEX_ORANGE_UNASSUMING%
@set ANSI_PREFERRED_CURSOR_COLOR_HEX=%HEX%
@set ANSI_PREFERRED_CURSOR_SHAPE=%ANSI_CURSOR_CHANGE_TO_BLOCK_BLINKING%
@echos %@SET_CURSOR_COLOR_BY_HEX[%ANSI_PREFERRED_CURSOR_COLOR_HEX]%ANSI_PREFERRED_CURSOR_SHAPE%
