@echo off
set SECONDS=%1
call val-env-var SECONDS "Must provide number of seconds to pause when invoking %0 ... And optional 2nd parameter of your pause message"

if "%2" ne "" (set MSG=%@UNQUOTE[%2])
if "%2" eq "" (set MSG=Press any key when ready...)

set NUM_ARROWS=%@EVAL[%@LEN[%MSG] / 2 + .5]
                   set DOWNLEFTARROWS=
repeat %NUM_ARROWS set DOWNLEFTARROWS=%DOWNLEFTARROWS%%EMOJI_DOWN_LEFT_ARROW%

%COLOR_PAUSE%
set TIME_MSG=%DOWNLEFTARROWS% %EMOJI_ALARM_CLOCK% will continue in %FAINT_OFF%%ITALICS_ON%%BLINK_ON%%ANSI_BRIGHT_RED%%SECONDS%%ANSI_COLOR_PAUSE%%BLINK_OFF%%ITALICS_OFF%%FAINT_ON% seconds...%FAINT_OFF% %EMOJI_ALARM_CLOCK%
set TIME_MSG_ERASER=%ANSI_ERASE_LINE%
set PAUSE_MESSAGE=%ANSI_COLOR_PAUSE%%EMOJI_PAUSE_BUTTON% %MSG%%FAINT_ON%%ANSI_POSITION_SAVE%     %ANSI_MOVE_UP_1%%@ANSI_MOVE_TO_COL[1]%EMOJI_PAUSE_BUTTON% %TIME_MSG%%ANSI_POSITION_RESTORE% %ANSI_POSITION_SAVE%
echo.
inkey /C /W%SECONDS% %PAUSE_MESSAGE% %%unused_variable
echo %ANSI_POSITION_RESTORE%%EMOJI_CHECK_MARK%    %ANSI_MOVE_UP_1%%@ANSI_MOVE_TO_COL[1]%TIME_MSG_ERASER%
