@Echo OFF

REM call debug "Setting emojis..."

if "%1" eq "force"               (goto :Main_Branch)
if  "1" eq %EMOJIS_HAVE_BEEN_SET (goto :Already_Set)
if "%1" eq "generate"            (fix_unicode_filenames.py script|sort|uniq >%bat%\emoji.env.generated.on.%_ISODATE.dont.forget.to.move.manual.stuff.at.end.of.previous.versions)

:Main_Branch

setdos /X-7 

REM {BIG SECTION OF CUSTOM EMOJI ANSI GENERATIONM CODE MOVED TO SET-COLORS.BAT}

    setdos /X7                         %+ rem timer
    set /r c:\bat\emoji.env            %+ rem Load emojis generated by our script: %+ rem timer 
    set EMOJIS_HAVE_BEEN_SET=1         %+ rem Flag that the emojis have been defined so we don't do this over and over


:Already_Set
:END
setdos /X0
