@Echo OFF

    SET REGEX_TASKLIST_WINAMP=Winamp
    SET REGEX_KILLPROC_WINAMP=winamp*
    SET REGEX_TASKLIST_LASTFM=Last.fm
    SET REGEX_KILLPROC_LASTFM=last.fm*
    SET REGEX_TASKLIST_LYRICS=MiniLyrics
    SET REGEX_KILLPROC_LYRICS=MiniLyrics

