"""Self-contained additions to PAFPlayer's existing browser interface."""

HTML = r'''
<style>
.workflow-tools{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:10px 0}.workflow-tools input[type=text]{min-width:190px;max-width:100%}.workflow-note{font-size:.82rem;color:#b4c6db}.workflow-status{white-space:pre-wrap;overflow-wrap:anywhere;color:#a9dfbd;min-height:1.4em}.queue-editor-scroll{max-height:390px;overflow:auto}.queue-editor-table{border-collapse:collapse;width:100%;font-size:.85rem}.queue-editor-table td{padding:7px;border-bottom:1px solid #2c3e51}.queue-editor-table tr.selected{background:#173d51}.queue-editor-table tr.current{border-left:4px solid #5ad88f}.queue-editor-table tr.missing{color:#ffa79b}.queue-editor-table tr[draggable]{cursor:grab}.queue-badge{border:1px solid #47617a;border-radius:8px;font-size:.72rem;padding:2px 5px;margin:3px;display:inline-block}.drop-active{outline:5px dashed #4bc8e9;outline-offset:-8px}#workflowLogs{max-height:320px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;font:12px Consolas,monospace;background:#060d15;padding:10px}#repairResults fieldset{margin:12px 0;border:1px solid #49617c}#repairResults label{display:block;margin:8px;overflow-wrap:anywhere}.workflow-secret{font:12px monospace;overflow-wrap:anywhere}.workflow-tools [hidden]{display:none!important}
</style>
<div class="group" id="queueEditorSection">
 <h3>Queue editor · Experimental</h3>
 <p class="workflow-note">Drag rows to reorder; use checkboxes for multiple tracks. Changes are confirmed by the player. Audio files are never deleted.</p>
 <div class="workflow-tools"><input id="queueSearch" type="search" placeholder="Search playlist"><select id="queueFilter"><option value="all">All tracks</option><option value="missing">Missing</option><option value="queued">Play-next queue</option><option value="monitored">Monitored imports</option><option value="uploaded">Uploads</option></select><button id="queueSelectAll">Select visible</button><button id="queueClearSelection">Clear selection</button></div>
 <div class="workflow-tools" id="queueEditorButtons"><button data-queue-op="next">Play next</button><button data-queue-op="after-current">Play after current</button><button data-queue-op="top">Move top</button><button data-queue-op="bottom">Move bottom</button><button data-queue-op="remove">Remove from queue</button><button data-queue-op="undo">Undo</button><button id="queueSave">Save as new playlist</button><button id="queueRepair">Repair missing files</button></div>
 <p id="queueReason" class="workflow-note"></p><p id="explicitNext" class="workflow-note"></p>
 <div class="queue-editor-scroll"><table class="queue-editor-table"><tbody id="queueEditorRows"></tbody></table></div>
 <details><summary>Queue history / diff</summary><pre id="queueHistory" class="workflow-status"></pre></details>
 <p class="workflow-note">Drop files or folders anywhere to queue next. Local files are matched against this playlist and configured library roots; ambiguous matches require upload or library configuration.</p><input type="file" id="workflowFiles" multiple><input type="file" id="workflowFolder" webkitdirectory multiple>
 <p id="workflowStatus" class="workflow-status" role="status"></p>
</div>
<div class="group" id="workflowSecuritySection"><h3>Security</h3>
 <label><input type="checkbox" id="allowRemoteUploads">Allow uploads and paired remote drops / queue workflows</label>
 <p class="workflow-note">100 MiB per file; 512 MiB managed quota. Supported audio is validated. Unused uploads expire after 24 hours and go to the Recycle Bin. Remote writes require the pairing token below. Only this computer can change Security.</p>
 <details id="workflowPairing"><summary>Pair another browser (keep this token private)</summary><p class="workflow-secret" id="workflowToken"></p></details><button id="workflowPairRemote">Enter pairing token</button>
 <div class="workflow-tools"><label>Library/search roots, one per line <textarea id="workflowRoots" rows="3"></textarea></label><button id="workflowSaveRoots">Save library roots</button></div>
</div>
<div class="group" id="workflowRepairSection"><h3>Missing-file repair · Experimental</h3>
 <div class="workflow-tools"><input type="text" id="repairPlaylist" placeholder="Playlist path (blank = active queue)"><input type="text" id="repairRoot" placeholder="Additional search root"><label><input type="checkbox" id="repairRecursive">Recursive search</label><button id="repairPreview">Find candidates / dry run</button></div>
 <label><input type="checkbox" id="repairPlaylistOnly">Update playlist only</label><p class="workflow-note">Nothing changes until you select replacements and approve them. Filename similarity alone is ambiguous.</p>
 <div id="repairResults"></div><button id="repairApply">Approve selected replacements as a batch</button><pre id="repairStatus" class="workflow-status"></pre>
</div>
<div class="group" id="workflowMonitorSection"><h3>Folder monitoring · Experimental</h3>
 <div class="workflow-tools"><textarea id="monitorRoots" rows="3" placeholder="Folders, one per line"></textarea><select id="monitorMode"><option value="index">Index only</option><option value="library">Add to general library</option><option value="playlist">Add to selected playlist</option></select><input id="monitorPlaylist" type="text" placeholder="Playlist destination"><label><input type="checkbox" id="monitorRecursive">Recursive</label><button id="monitorStart">Start monitoring</button></div>
 <div class="workflow-tools"><button data-monitor-op="pause">Pause</button><button data-monitor-op="resume">Resume</button><button data-monitor-op="scan">Scan now</button><button id="monitorPreview">Dry-run preview</button><button id="monitorLibraryQueue">Queue selected library matches</button><input type="search" id="monitorLibrarySearch" placeholder="Library filename search"></div><pre id="monitorStatus" class="workflow-status"></pre>
</div>
<div class="group" id="workflowLogsSection"><h3>Live log viewer · Experimental</h3><div class="workflow-tools"><button id="logsPause">Resume streaming</button><select id="logsLevel"><option value="">All levels</option><option>TRACE</option><option>INFO</option><option>ERROR</option></select><input id="logsCategory" placeholder="Category"><input id="logsSearch" type="search" placeholder="Search redacted messages"></div><p class="workflow-note">Paths, credentials and upload details are redacted. At most 200 records per poll and 1,000 visible records.</p><pre id="workflowLogs"></pre></div>
<div class="group" id="workflowDiscordSection"><h3>Discord Now Playing · Optional</h3><label><input id="discordEnabled" type="checkbox">Publish Now Playing to my configured Discord webhook</label><br><label><input id="discordLocalTitles" type="checkbox">Allow titles/artists of local tracks to be shared</label><p class="workflow-note">Off until explicitly enabled. Set PAFPLAYER_DISCORD_WEBHOOK in the player's environment; the secret is never sent to this page. Paths and audio URLs are never published. Tracks marked private are excluded.</p><button id="discordSave">Save Discord choice</button><p id="discordStatus" class="workflow-status"></p></div>
'''

SCRIPT = r'''
<script>
(()=>{
 const $=id=>document.getElementById(id);let state=null,selected=new Set(),busy=false,dragged=[],preview=null,logPaused=true,logCursor=0,logs=[],lastSelection=-1;
 let token=sessionStorage.getItem('paf-workflow-token')||'';
 const status=(message,bad=false)=>{$('workflowStatus').textContent=String(message);$('workflowStatus').style.color=bad?'#ffa79b':'#a9dfbd'};
 const lines=value=>String(value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
 async function api(op,payload){const r=await fetch('/api/workflows/'+op,payload===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json','X-PAF-Workflow-Token':token},body:JSON.stringify(payload)});const result=await r.json();if(!r.ok)throw new Error(result.error||r.statusText);return result}
 async function job(value){if(!value.job)return value;for(let i=0;i<600;i++){await new Promise(resolve=>setTimeout(resolve,500));const v=await api('job/'+value.job);if(v.state==='done')return v.result;if(v.state==='error')throw new Error(v.error)}throw new Error('Background job is still running; refresh status later')}
 function source(path){return (state?.index?.[path]||state?.index?.[path.replace(/\//g,'\\').toLowerCase()])?.source||''}
 function missing(path){return !!state?.queue?.missing?.includes(path)}
 function visible(){if(!state)return [];const q=$('queueSearch').value.toLowerCase(),filter=$('queueFilter').value;return state.queue.entries.map((path,index)=>({path,index})).filter(x=>x.path.toLowerCase().includes(q)&&(filter==='all'||filter==='missing'&&missing(x.path)||filter==='queued'&&state.queue.next.includes(x.path)||source(x.path)===filter))}
 function render(){
  if(!state)return;const body=$('queueEditorRows');body.textContent='';const rows=visible();
  for(const {path,index} of rows.slice(0,1500)){const tr=document.createElement('tr');tr.draggable=true;tr.classList.toggle('selected',selected.has(path));tr.classList.toggle('current',path===state.queue.current);tr.classList.toggle('missing',missing(path));
   const check=document.createElement('input');check.type='checkbox';check.checked=selected.has(path);check.onchange=e=>{if(e.shiftKey&&lastSelection>=0){const start=Math.min(lastSelection,index),end=Math.max(lastSelection,index);for(const value of state.queue.entries.slice(start,end+1))if(check.checked)selected.add(value);else selected.delete(value)}else if(check.checked)selected.add(path);else selected.delete(path);lastSelection=index;render()};
   const td=document.createElement('td');td.appendChild(check);const label=document.createElement('td');label.textContent=(index+1)+'. '+path.split(/[\\/]/).pop();label.title=path;
   for(const text of [path===state.queue.current?'Current':'',state.queue.next.includes(path)?'Play next #'+(state.queue.next.indexOf(path)+1):'',missing(path)?'Missing':'',source(path),state.queue.shuffled?'Shuffled':''].filter(Boolean)){const badge=document.createElement('span');badge.className='queue-badge';badge.textContent=text;label.appendChild(badge)}tr.append(td,label);
   tr.ondragstart=e=>{dragged=selected.has(path)?[...selected]:[path];e.dataTransfer.setData('application/x-paf-queue',JSON.stringify(dragged));e.dataTransfer.effectAllowed='move'};tr.ondragover=e=>{if([...e.dataTransfer.types].includes('application/x-paf-queue'))e.preventDefault()};tr.ondrop=e=>{if(![...e.dataTransfer.types].includes('application/x-paf-queue'))return;e.preventDefault();e.stopPropagation();queueEdit('move',dragged,{index:state.queue.entries.slice(0,index).filter(x=>!dragged.includes(x)).length})};body.appendChild(tr);
  }
  $('queueReason').textContent=state.queue.reason+(rows.length>1500?' · Showing first 1,500 matches; narrow your search.':'');$('explicitNext').textContent='Explicit next: '+(state.queue.next.map(x=>x.split(/[\\/]/).pop()).join(' → ')||'none');
  $('queueHistory').textContent=(state.history||[]).map(x=>new Date(x.time*1000).toLocaleTimeString()+' '+x.operation+'\n+ '+x.added.join('\n+ ')+'\n− '+x.removed.join('\n− ')).join('\n');
 }
 async function refresh(){if(busy)return;try{const value=await api('status');const first=!state;state=value;if(state.token){token=state.token;sessionStorage.setItem('paf-workflow-token',token)}
  if(first){$('allowRemoteUploads').checked=!!state.settings.remote_uploads;$('workflowRoots').value=(state.settings.library_roots||[]).join('\n');$('discordEnabled').checked=!!state.settings.discord_enabled;$('discordLocalTitles').checked=!!state.settings.discord_share_local_titles}
  $('allowRemoteUploads').disabled=!state.local;$('workflowSaveRoots').disabled=!state.local;$('workflowPairing').hidden=!state.local;$('workflowToken').textContent=state.token||'';$('workflowPairRemote').hidden=!!state.local;
  $('monitorStatus').textContent=state.monitor?JSON.stringify(state.monitor,null,2):'Monitoring is off';$('discordStatus').textContent=state.discord||'Disabled';render();
 }catch(e){status(e,true)}}
 async function queueEdit(op,paths=[...selected],extra={}){if(!state||busy)return;const revision=state.queue.revision;busy=true;status('Waiting for player confirmation…');
  // Optimistic removal/reordering is visibly pending until the server confirms.
  if(op==='remove')state.queue.entries=state.queue.entries.filter(x=>!paths.includes(x));render();
  try{const result=await api('queue',{op,paths,revision,...extra});status(result.saved_path?'Saved playlist: '+result.saved_path:'Queue change confirmed');if(op==='remove')selected.clear()}catch(e){status(e,true)}finally{busy=false;await refresh()}}
 $('queueSearch').oninput=render;$('queueFilter').onchange=render;$('queueSelectAll').onclick=()=>{visible().forEach(x=>selected.add(x.path));render()};$('queueClearSelection').onclick=()=>{selected.clear();render()};
 for(const b of document.querySelectorAll('[data-queue-op]'))b.onclick=()=>queueEdit(b.dataset.queueOp);
 $('queueSave').onclick=()=>{const name=prompt('New playlist filename:','queue.m3u8');if(name)queueEdit('save',[],{name})};
 $('allowRemoteUploads').onchange=async e=>{try{await api('settings',{remote_uploads:e.target.checked});status('Security setting saved');await refresh()}catch(err){e.target.checked=!e.target.checked;status(err,true)}};
 $('workflowSaveRoots').onclick=async()=>{try{await api('settings',{library_roots:lines($('workflowRoots').value)});status('Library roots saved')}catch(e){status(e,true)}};
 $('workflowPairRemote').onclick=()=>{const value=prompt('Paste the pairing token shown on the player computer:');if(value){token=value.trim();sessionStorage.setItem('paf-workflow-token',token);status('Pairing token stored for this browser session')}};
 async function upload(file){if(!state?.settings.remote_uploads)throw new Error('Uploads are disabled in Security');if(file.size>100*1024*1024)throw new Error(file.name+' exceeds 100 MiB');const r=await fetch('/api/workflows/upload',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-PAF-Workflow-Token':token,'X-File-Name':encodeURIComponent(file.name)},body:file});const data=await r.json();if(!r.ok)throw new Error(data.error);if(!data.queued)throw new Error('Uploaded, but no active playlist is available; open a playlist first')}
 async function dropFiles(files){try{if(!files.length)return;if(files.length>1000)throw new Error('Drop at most 1,000 files at once');status('Resolving dropped media…');let unresolved=files;
  if(state?.local){const result=await job(await api('resolve-drop',{files:files.map(f=>({name:f.name,size:f.size}))}));const names=new Set(result.unresolved.map(x=>x.name));unresolved=files.filter(x=>names.has(x.name));status(result.queued+' local files queued')}
  if(unresolved.length){if(!state?.settings.remote_uploads)throw new Error('Some files are not uniquely indexed. Add their library root, or enable uploads in Security.');if(!confirm('Upload '+unresolved.length+' files to the temporary managed area and queue them?'))return;for(const file of unresolved){status('Uploading '+file.name);await upload(file)}}status('Drop completed');await refresh();
 }catch(e){status(e,true)}}
 async function walk(entry,output,depth=0){if(depth>20||output.length>=1000)return;if(entry.isFile){output.push(await new Promise((resolve,reject)=>entry.file(resolve,reject)))}else if(entry.isDirectory){const reader=entry.createReader();while(output.length<1000){const batch=await new Promise((resolve,reject)=>reader.readEntries(resolve,reject));if(!batch.length)break;for(const child of batch)await walk(child,output,depth+1)}}}
 window.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();document.body.classList.add('drop-active')}});window.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('drop-active')});
 window.addEventListener('drop',async e=>{if(![...e.dataTransfer.types].includes('Files'))return;e.preventDefault();document.body.classList.remove('drop-active');const files=[];try{const entries=[...e.dataTransfer.items].map(x=>x.webkitGetAsEntry?.()).filter(Boolean);if(entries.length){for(const entry of entries)await walk(entry,files)}else files.push(...e.dataTransfer.files);await dropFiles(files)}catch(err){status(err,true)}});
 $('workflowFiles').onchange=e=>dropFiles([...e.target.files]);$('workflowFolder').onchange=e=>dropFiles([...e.target.files]);
 async function findRepairs(){try{$('repairStatus').textContent='Searching…';preview=await job(await api('repair-preview',{playlist:$('repairPlaylist').value.trim()||null,roots:lines($('repairRoot').value),recursive:$('repairRecursive').checked}));const host=$('repairResults');host.textContent='';for(const item of preview.items){const box=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=item.missing;box.appendChild(legend);const choices=document.createElement('select');choices.dataset.missing=item.missing;const skip=document.createElement('option');skip.value='';skip.textContent='Leave unchanged';choices.appendChild(skip);for(const candidate of item.candidates){const opt=document.createElement('option');opt.value=candidate.path;opt.textContent='['+candidate.confidence+' '+candidate.score+'] '+candidate.path+' — '+candidate.evidence.join('; ');choices.appendChild(opt)}box.appendChild(choices);const one=document.createElement('button');one.textContent='Approve this item';one.onclick=()=>applyRepairs([choices]);box.appendChild(one);host.appendChild(box)}$('repairStatus').textContent=preview.items.length+' missing entries. Review candidates before approving.'}catch(e){$('repairStatus').textContent=String(e)}}
 async function applyRepairs(selects){const approved={};for(const select of selects)if(select.value)approved[select.dataset.missing]=select.value;if(!Object.keys(approved).length)return;if(!confirm('Apply these '+Object.keys(approved).length+' selected replacements? Audio files will not be changed.'))return;try{const result=await job(await api('repair-apply',{id:preview.id,approved,dry_run:false,playlist_only:$('repairPlaylistOnly').checked}));$('repairStatus').textContent=JSON.stringify(result,null,2);await refresh();await findRepairs()}catch(e){$('repairStatus').textContent=String(e)}}
 $('repairPreview').onclick=findRepairs;$('repairApply').onclick=()=>applyRepairs([...$('repairResults').querySelectorAll('select')]);$('queueRepair').onclick=()=>{$('repairPlaylist').value='';$('workflowRepairSection').scrollIntoView({block:'start'});findRepairs()};
 $('monitorStart').onclick=async()=>{try{await api('monitor',{op:'start',roots:lines($('monitorRoots').value),mode:$('monitorMode').value,playlist:$('monitorPlaylist').value||null,recursive:$('monitorRecursive').checked});await refresh()}catch(e){status(e,true)}};
 async function monitorOp(op,dry_run=false){try{const result=await job(await api('monitor',{op,dry_run}));status(JSON.stringify(result));await refresh()}catch(e){status(e,true)}}for(const b of document.querySelectorAll('[data-monitor-op]'))b.onclick=()=>monitorOp(b.dataset.monitorOp);$('monitorPreview').onclick=()=>monitorOp('scan',true);
 $('monitorLibraryQueue').onclick=async()=>{try{const search=$('monitorLibrarySearch').value.trim();if(!search)return;const result=await api('library',{search,preview:true});if(!result.items.length){status('No library matches');return}if(!confirm('Queue these '+result.items.length+' matches?\n'+result.items.map(x=>x.filename).join('\n')))return;await api('library',{search,approved:result.items.map(x=>x.path)});await refresh()}catch(e){status(e,true)}};
 async function pollLogs(){if(logPaused)return;try{const query=new URLSearchParams({after:String(logCursor),level:$('logsLevel').value,category:$('logsCategory').value,search:$('logsSearch').value});const result=await api('logs?'+query);logCursor=result.cursor;logs.push(...result.records);logs=logs.slice(-1000);$('workflowLogs').textContent=logs.map(x=>new Date(x.time*1000).toLocaleTimeString()+' '+x.level+' '+x.message).join('\n')}catch(e){$('workflowLogs').textContent=String(e)}}
 $('logsPause').onclick=()=>{logPaused=!logPaused;$('logsPause').textContent=logPaused?'Resume streaming':'Pause streaming';pollLogs()};for(const id of ['logsLevel','logsCategory','logsSearch'])$(id).oninput=()=>{logCursor=0;logs=[];pollLogs()};
 $('discordSave').onclick=async()=>{try{const result=await api('discord',{enabled:$('discordEnabled').checked,share_local_titles:$('discordLocalTitles').checked});$('discordStatus').textContent=result.status}catch(e){$('discordStatus').textContent=String(e)}};
 // Keep the editor within the existing Playlist panel.
 $('playlistSection')?.appendChild($('queueEditorSection'));
 refresh();setInterval(()=>{if(!document.hidden)refresh()},3000);setInterval(()=>{if(!document.hidden)pollLogs()},1000);
})();
</script>
'''

def augment(page):
    from PAFPlayer_windows_ui import augment as windows_ui
    page=windows_ui(page)
    return page.replace('<div class="group section-global-config" id="globalConfigSection">',HTML+'<div class="group section-global-config" id="globalConfigSection">',1).replace('</body>',SCRIPT+'</body>',1)
